### ISSUE TITLE
Possible 2.0.0 regression with isolator

### ISSUE THREAD

**Issue by geoffharcourt** [palkan/anyway_config#56] opened 2020-04-14 20:25 UTC
## What did you do?

Updated anyway_config from 1.4.4 -> 2.0.0

## What did you expect to happen?

My CI suite to run!

## What actually happened?

It crashes on suite start when I try to require isolator:

```

An error occurred while loading spec_helper.
--
474 | Failure/Error: require "isolator"
474 |  
475 | FrozenError:
477 | can't modify frozen Array
477 | # ./spec/spec_helper.rb:26:in `<main>'

```

## Additional context

Our Gemfile:
```
gem "isolator", require: false
```

isolator 0.6.2
sniffer 0.4.0
anyway_config 2.0.0

## Environment

**Ruby Version:**

2.6.6

**Framework Version (Rails, whatever):**

Rails 6.0.2.2
RSpec 3.9.0

**Anyway Config Version:**

**Comment by palkan** [comment] 2020-04-15 07:28
Thanks for the report!

The error seems irrelevant (`FrozenError: can't modify frozen Array` usually happens when `spec_helper`/`rails_helper` fails to load and the next attempt initialize the Rails application for the second time).

To catch the exact reason why Rails application fails to initialize, you need to wrap the `require ".../environment.rb"` with the following code:

```ruby
begin
  require File.expand_path("../../config/environment", __FILE__)
rescue => e
  # Fail fast if application couldn't be loaded
  $stdout.puts "Failed to load the app: #{e.message}\n#{e.backtrace.take(15).join("\n")}"
  exit(1)
end
```

Could you please try to do that? That should show us the exact reason.

**Comment by geoffharcourt** [comment] 2020-04-15 09:42
Hi!

I wrapped both instances of my require `config/environment` with the rescue, but got the exact same error. It still failed at the isolator require with no change in output (other than the line number).

Here's our `spec_helper`:

```
ENV["RAILS_ENV"] ||= "test"

begin
  require File.expand_path("../config/environment", __dir__)
rescue => e
  # Fail fast if application couldn't be loaded
  $stdout.puts "Failed to load the app: #{e.message}\n#{e.backtrace.take(15).join("\n")}"
  exit(1)
end

require "rspec/rails"
require "knapsack_pro"
if ENV["CI"].present?
  KnapsackPro::Adapters::RSpecAdapter.bind
end
require "shoulda/matchers"
require "devise/test_helpers"
require "rack_session_access/capybara"
require "capybara/rspec"
require "support/page"
require "paperclip/matchers"
require "test_prof/recipes/rspec/let_it_be"

Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }

# [NOTE] This must be required after Sidekiq or else it won't observe enqueueing
# of Sidekiq jobs in fake mode.
require "isolator"
Isolator.adapters.sidekiq.ignore_if { Thread.current[:sidekiq_postpone] }
```

**Comment by palkan** [comment] 2020-04-15 11:19
What is on the line ./spec/spec_helper.rb:26 in the original case?

**Comment by geoffharcourt** [comment] 2020-04-15 13:03
`require "isolator"`

**Comment by palkan** [comment] 2020-04-15 17:50
Couldn't reproduce so far.

Are there more exception backtrace lines?

Could you try to wrap `require "isolator"` into the code I proposed above to print the exception?

**Comment by geoffharcourt** [comment] 2020-04-15 17:53
Paydirt!

```
Failed to load the app: can't modify frozen Array
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/anyway_config-2.0.0/lib/anyway/loaders.rb:67:in `insert'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/anyway_config-2.0.0/lib/anyway/loaders.rb:67:in `insert_at'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/anyway_config-2.0.0/lib/anyway/loaders.rb:37:in `insert_after'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/anyway_config-2.0.0/lib/anyway/rails.rb:15:in `<main>'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/anyway_config-2.0.0/lib/anyway_config.rb:37:in `<main>'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/geoff/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
No examples found.
```

**Comment by palkan** [comment] 2020-04-15 19:16
Thanks!

Fixed by https://github.com/palkan/anyway_config/commit/60a74042c1cd27979fd277c4ca422059fd4df3e2 and release in 2.0.1

**Comment by geoffharcourt** [comment] 2020-04-15 19:17
Thanks @palkan! I love your OSS work and I really appreciate you looking into this and resolving it so quickly.

**Closed by palkan** 2020-04-15 19:16 UTC
Labels: awaiting response, investigation required
